sonar.projectKey=dynatrace-oss_dtmgd
sonar.organization=dynatrace-oss
sonar.host.url=https://sonarcloud.io

sonar.projectName=dtmgd
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/*_test.go,vendor/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
